In [1]:
import numpy as np

In [3]:
class NearestNeighbor:
    def __init__(self):
        pass
    
    def train(self, X, y):
        """ X is N x D where each row is an example. Y is 1-demension of size N """
        # the nearest neighbour classifier simply remembers all the training data
        self.Xtr = X
        self.ytr = y
    
    def predict(self, X):
        """ X is N x D where each row is an example we wish to predict label for """
        num_test = X.shape[0]
        # lets make sure that the output typw matches the input type
        Ypred = np.zeros(num_test, dtype = self.ytr.dtype)

        # loop over all test rows
        for i in range(num_test):
            # find the nearest training image to the i'th test image
            # using the L1 distance (sum of absolute value differences)
            distances = np.sum(np.abs(self.Xtr - X[i, :]), axis = 1)
            min_index = np.argmin(distances) # get the index with smallest distance
            Ypred[i] = self.ytr[min_index] # predict the label of the nearest example
        
        return Ypred

In [4]:

Xtr = np.array([[25, 23, 26, 74],
            [15, 12, 14, 16],
            [25, 23, 46, 78],
            [58, 78, 45, 36],
            [48, 15, 75, 16]])
X = np.array([[15, 12, 18, 19],
[15, 48, 19, 15],
[78, 15, 75, 12]])
y = np.array([12, 15, 78, 19, 45])

np.abs(Xtr - X[1, :]), np.sum(np.abs(Xtr - X[1, :]), axis = 1)


(array([[10, 25,  7, 59],
        [ 0, 36,  5,  1],
        [10, 25, 27, 63],
        [43, 30, 26, 21],
        [33, 33, 56,  1]]),
 array([101,  42, 125, 120, 123]))

In [6]:
model = NearestNeighbor()
model.train(Xtr,y)
model.predict(X)

array([15, 15, 45])